# Generated by Django 5.0.6 on 2024-06-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='конечная цена'),
        ),
    ]
